# Generated by Django 2.2.1 on 2019-08-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vegtables',
            name='image',
            field=models.ImageField(default='up_images/vegtables/no-img.jpg', upload_to='up_images/vegtables'),
        ),
    ]
