# Generated by Django 2.2.1 on 2019-08-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_vegtables_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='vegtables',
            name='Discount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
