# Generated by Django 2.2.1 on 2019-08-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_vegtables_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vegtables',
            name='kind',
            field=models.CharField(choices=[('green', 'GREEN'), ('blue', 'BLUE'), ('red', 'RED'), ('orange', 'ORANGE'), ('black', 'BLACK')], default='green', max_length=6),
        ),
    ]
