# Generated by Django 2.2.1 on 2019-08-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20190811_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vegtables',
            name='kind',
            field=models.CharField(choices=[('vegetables', 'Vegetables'), ('fruits', 'Fruits'), ('juice', 'Juice'), ('dried', 'Dried')], default='green', max_length=10),
        ),
    ]
