# Generated by Django 2.2.1 on 2019-08-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_vegtables_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vegtables',
            name='image',
            field=models.ImageField(default='up_images/vegtables/no-img.jpg', upload_to='media/vegtables'),
        ),
    ]
