# Generated by Django 2.2.1 on 2019-08-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20190811_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vegtables',
            name='image',
            field=models.ImageField(default='static/media/vegtables/no-img.jpg', upload_to='static/media/vegtables'),
        ),
    ]
