# Generated by Django 2.2.1 on 2019-08-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='wish',
            field=models.BooleanField(),
        ),
    ]
